name: checkout
on: push

jobs:

  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: inst
        run: npm instull
    
      
